name: Check Secret Value

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Display secret length
        run: |
          SECRET_VALUE="${{ secrets.SECRET_123 }}"
          echo "Secret length: $(echo -n "$SECRET_VALUE" | wc -c)"

      - name: Encode secret in Base64
        run: |
          echo "Base64 Encoded: $(echo -n '${{ secrets.SECRET_123 }}' | base64)"

      - name: Store secret in a file
        run: |
          echo "${{ secrets.SECRET_123 }}" > secret.txt
          echo "Secret written to file (not printed in logs)"

      - name: Verify Secret Exists
        run: |
          if [[ -s secret.txt ]]; then
            echo "Secret is stored successfully!"
          else
            echo "Secret is empty!"
          fi
