name: Check JSON Secret

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Display Secret Length
        run: |
          SECRET_VALUE='${{ secrets.SECRET_123 }}'
          echo "Secret length: $(echo -n "$SECRET_VALUE" | wc -c)"

      - name: Store Secret JSON in a File
        run: |
          echo '${{ secrets.SECRET_123 }}' | tr -d '\r' > secret.json
          echo "Secret JSON written to file (not printed in logs)"

      - name: Validate JSON Format
        run: |
          if jq empty secret.json > /dev/null 2>&1; then
            echo "Valid JSON format detected."
          else
            echo "Invalid JSON format!"
            exit 1
          fi

      - name: Extract Values from JSON
        run: |
          TOKEN=$(jq -r '.token' secret.json)
          REFRESH_TOKEN=$(jq -r '.refresh_token' secret.json)
          CLIENT_ID=$(jq -r '.client_id' secret.json)
          CLIENT_SECRET=$(jq -r '.client_secret' secret.json)
          SCOPES=$(jq -r '.scopes' secret.json)

          echo "Token length: ${#TOKEN}"
          echo "Refresh Token length: ${#REFRESH_TOKEN}"
          echo "Client ID length: ${#CLIENT_ID}"
          echo "Client Secret length: ${#CLIENT_SECRET}"
          echo "Scopes: $SCOPES"

      - name: Upload Secret JSON File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-json-file
          path: secret.json
          retention-days: 1  # Keeps artifact for 1 day

  verify-secret:
    needs: check-secret  # Runs after the first job completes
    runs-on: ubuntu-latest

    steps:
      - name: Download Secret File
        uses: actions/download-artifact@v4
        with:
          name: secret-json-file

      - name: Verify Secret File Exists
        run: |
          if [[ -s secret.json ]]; then
            echo "Secret JSON file was successfully transferred!"
            cat secret.json | jq '.'
          else
            echo "Error: Secret JSON file is missing or empty!"
            exit 1
          fi
